#!/usr/bin/env bash
#displays numbers from 1 to 20.

NUMBER=1
while((NUMBER<=20));do
	echo "$NUMBER"
	case $NUMBER in
		4) echo "bad luck from china"
			;;
		9) echo "bad luck from Japan"
			;;
		17) echo "bad luck from Italy"
			;;

	esac
	((NUMBER++))
done;
