#!/usr/bin/env bash
#starts stop restart script depending on the argument passed

function startup(){
       bash ./manage_my_procecess & 
      echo "$!" > /var/run/my_process.pid
}

function stopnow(){
	[ -e "/var/run/my_process.pid" ] && pkill -f './manage_my_process' && rm /var/run/my_process.pid

}

function restartnow(){
	stopnow
	startup
	echo "manage_my_process restarted"

}
if [ $# -eq 1 ]
then 
	OPTION="$1"
	case $OPTION in
		"start")
			#stopnow
			stopnow
			echo "manage_my_process stopped"
			;;
		"restart")
			restarnow
			;;
		*)
			echo "Usage: manage_my_process {start|stop|restart}"
			;;
	esac
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
